// Generated by CoffeeScript 1.10.0
(function() {
  var Client, Cloudant, Manager, ObjectId, async, config, express, mongoose, router;

  express = require('express');

  router = express.Router();

  mongoose = require('mongoose');

  ObjectId = mongoose.Types.ObjectId;

  Manager = mongoose.model('Manager');

  Client = mongoose.model('Client');

  Cloudant = require('cloudant');

  async = require('async');

  config = require('../config.coffee');

  router.get('/', function(req, res, next) {
    var cloudant, kv_content, resData;
    cloudant = Cloudant({
      account: config.cloudant_user,
      password: config.cloudant_password
    });
    kv_content = cloudant.db.use('kv_content');
    resData = [];
    // START HERE;
    // FINISH HERE;
    return res.status(200).json(resData);
  });

  router.post('/', function(req, res, next) {
    return async.waterfall([
      function(callback) {
        var client;
        client = new Client({
          name: req.body.name
        });
        return client.save(callback);
      }, function(savedClient, nInserted, callback) {
        return callback(null, savedClient);
      }
    ], function(err, result) {
      if (err) {
        console.log(err);
        return res.status(500).json(err);
      } else {
        console.log(result);
        return res.status(200).json(result);
      }
    });
  });

  module.exports = router;

}).call(this);
