// Generated by CoffeeScript 1.10.0
(function() {
  var app, bodyparser, express, http, models, mongoose;

  http = require('http');

  mongoose = require('mongoose');

  express = require('express');

  bodyparser = require('body-parser');

  models = require('./models/index.js');

  mongoose.connect('mongodb://localhost/six');

  models.initialize();

  app = express();

  app.use(bodyparser.json());

  app.use('/manager', require('./routes/manager.js'));

  app.use('/client', require('./routes/client.js'));

  http.createServer(app).listen(8080);

  console.log('magic happens');
}).call(this);
