// Generated by CoffeeScript 1.10.0
(function() {
  var ObjectId, Schema, mongoose;

  mongoose = require('mongoose');

  Schema = mongoose.Schema;

  ObjectId = Schema.Types.ObjectId;

  module.exports = function() {
    var ClientSchema;
    ClientSchema = new Schema({
      name: {
        type: String
      },
      interests: [
        {
          type: String
        }
      ]
    });
    return mongoose.model('Client', ClientSchema, 'clients');
  };

}).call(this);
