// Generated by CoffeeScript 1.10.0
(function() {
  var models;

  models = ['./manager.coffee', './client.coffee'];

  exports.initialize = function() {
    var i, len, model, results;
    results = [];
    for (i = 0, len = models.length; i < len; i++) {
      model = models[i];
      results.push(require(model)());
    }
    return results;
  };

}).call(this);
