// Generated by CoffeeScript 1.10.0
(function() {
  var ObjectId, Schema, mongoose;

  mongoose = require('mongoose');

  Schema = mongoose.Schema;

  ObjectId = Schema.Types.ObjectId;

  module.exports = function() {
    var ManagerSchema;
    ManagerSchema = new Schema({
      name: {
        type: String
      },
      clients: [
        {
          type: ObjectId,
          ref: 'Client'
        }
      ]
    });
    return mongoose.model('Manager', ManagerSchema, 'managers');
  };

}).call(this);
